# Generated by Django 4.2.5 on 2023-09-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CR', 'Создана'), ('ST', 'Запущена'), ('FI', 'Завершена')], default='CR', max_length=2, verbose_name='статус рассылки')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='время начала рассылки')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='время окончания рассылки')),
                ('period', models.CharField(choices=[('HR', 'Часовая'), ('DL', 'Ежедневная'), ('WK', 'Еженедельная')], max_length=2, verbose_name='периодичность')),
            ],
            options={
                'verbose_name': 'настройка',
                'verbose_name_plural': 'настройки',
            },
        ),
    ]
