# Generated by Django 4.2.5 on 2023-09-13 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_newslettersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mail.newslettersettings', verbose_name='настройка рассылки'),
            preserve_default=False,
        ),
    ]
