# Generated by Django 4.2.5 on 2023-10-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('mail', '0003_newsletter_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='clients',
            field=models.ManyToManyField(to='client.client', verbose_name='клиент'),
        ),
    ]
