# Generated by Django 4.2.5 on 2023-10-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_rename_settings_newsletter_mail_settings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersettings',
            options={'permissions': [('set_newsletter_status', 'Can change newsletter status')], 'verbose_name': 'настройка', 'verbose_name_plural': 'настройки'},
        ),
    ]
