# Generated by Django 4.2.5 on 2023-10-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_alter_newslettersettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('view_all', 'Can view all newsletters')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
