# Generated by Django 4.2.5 on 2023-10-17 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_alter_newsletter_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateTimeField(auto_now_add=True, verbose_name='время последней попытки')),
                ('server_answer', models.TextField(verbose_name='ответ сервера')),
                ('status', models.BooleanField(verbose_name='статус')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.newsletter', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
