# Generated by Django 4.2.5 on 2023-10-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_newsletterlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активность рассылки'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='job_id',
            field=models.CharField(default='', verbose_name='id задачи'),
        ),
        migrations.AlterField(
            model_name='newslettersettings',
            name='finish_time',
            field=models.DateTimeField(verbose_name='время окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='newslettersettings',
            name='start_time',
            field=models.DateTimeField(verbose_name='время начала рассылки'),
        ),
    ]
