# Generated by Django 4.2.5 on 2023-10-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_newsletter_is_active_newsletter_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterlogs',
            name='server_answer',
            field=models.TextField(blank=True, null=True, verbose_name='ответ сервера'),
        ),
        migrations.AlterField(
            model_name='newsletterlogs',
            name='status',
            field=models.CharField(max_length=50, verbose_name='статус'),
        ),
    ]
